---

- name: Installs nginx
  apt: pkg=nginx state=installed update_cache=true
  sudo: yes
  notify:
    - start nginx

- name: Configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: yes
  notify:
    - restart nginx

- name: Install app nginx config
  template: src=app.nginx.j2 dest=/etc/nginx/sites-available/default
  sudo: yes
  notify:
    - restart nginx
